POST http://127.0.0.1:3000/auth/register
content-type: application/json

{
    "email": "sample@gmail.com",
    "firstName": "Test",
    "lastName": "User",
}


###

GET http://127.0.0.1:3000/auth/users/1
